_BASE: ../vivit_fac_enc_ek100_submission.yaml
TRAIN:
  CHECKPOINT_PERIOD: 1
  EVAL_PERIOD: 1
  CHECKPOINT_FILE_PATH: ./checkpoints/vivit_fac_enc_b16x2_pt_k700_ft_ek100_32x224x224_4630_public.pyth
  FINE_TUNE: true
  BATCH_SIZE: 4

DATA:
  TRAIN_JITTER_SCALES: [336, 448]
  TRAIN_CROP_SIZE: 320
  TEST_SCALE: 320
  TEST_CROP_SIZE: 320

DATA_LOADER:
  NUM_WORKERS: 8

OUTPUT_DIR: output/vivit_fac_enc_ek100_submit