_BASE_RUN: ../../pool/run/training/finetune.yaml
_BASE_MODEL: ../../pool/backbone/r2p1d.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: UCF101
  CHECKPOINT_FILE_PATH: ""          # !!@2
  BATCH_SIZE: 48
TEST:
  ENABLE: true
  DATASET: UCF101
  BATCH_SIZE: 48
DATA:
  DATA_ROOT_DIR: /mnt/ziyuan/ziyuan/ucf101/videos/
  ANNO_DIR: /mnt/ziyuan/ziyuan/ucf101/annotations/
  MINUS_INTERVAL: false
VIDEO:
  HEAD:
    NUM_CLASSES: 101
    DROPOUT_RATE: 0.5
OPTIMIZER:
  BASE_LR: 0.0015
  WARMUP_START_LR: 0.00015
NUM_GPUS: 8