_BASE_RUN: ../../pool/run/training/finetune.yaml
_BASE_MODEL: ../../pool/backbone/r2p1d.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: HMDB51
  CHECKPOINT_FILE_PATH: ""          # !!@2
  BATCH_SIZE: 48
TEST:
  ENABLE: true
  DATASET: HMDB51
  BATCH_SIZE: 48
DATA:
  DATA_ROOT_DIR: /mnt/ziyuan/ziyuan/hmdb51/videos/
  ANNO_DIR: /mnt/ziyuan/ziyuan/hmdb51/anno_lists/
  MINUS_INTERVAL: false
VIDEO:
  HEAD:
    NUM_CLASSES: 51
    DROPOUT_RATE: 0.5
OPTIMIZER:
  BASE_LR: 0.00075
  WARMUP_START_LR: 0.000075
NUM_GPUS: 8