_BASE_RUN: ../../../pool/run/training/from_scratch.yaml
_BASE_MODEL: ../../../pool/backbone/r2p1d.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: HMDB51
  CHECKPOINT_FILE_PATH: ""
  BATCH_SIZE: 48
TEST:
  ENABLE: true
  DATASET: HMDB51
  BATCH_SIZE: 48
DATA:
  DATA_ROOT_DIR: /mnt/ziyuan/ziyuan/hmdb51/videos/
  ANNO_DIR: /mnt/ziyuan/ziyuan/hmdb51/anno_lists/
VIDEO:
  HEAD:
    NUM_CLASSES: 51
    DROPOUT_RATE: 0.5
OUTPUT_DIR: output/r2p1d_hmdb_from_scratch