_BASE_RUN: ../../pool/run/training/from_scratch_large.yaml
_BASE_MODEL: ../../pool/backbone/vivit_fac_enc.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: false
  DATASET: epickitchen100
  CHECKPOINT_FILE_PATH: ""
TEST:
  ENABLE: false
  DATASET: epickitchen100
  BATCH_SIZE: 4
SUBMISSION:
  ENABLE: true
  ACTION_CLASS_ENSUMBLE_METHOD: "sum" # sum or calculate
TASK_TYPE: submission
DATA:
  DATA_ROOT_DIR: /mnt/ziyuan/ziyuan/EPIC-KITCHENS-100/clips_512/
  ANNO_DIR: /mnt/ziyuan/ziyuan/EPIC-KITCHENS-100/annos/epic-kitchens-100-annotations-master/
  NUM_INPUT_FRAMES: 32
  SAMPLING_RATE: 2
  MULTI_LABEL: true
  TARGET_FPS: 60
VIDEO:
  HEAD:
    NAME: TransformerHeadx2
    NUM_CLASSES: [97, 300]
    DROPOUT_RATE: 0.5

DATA_LOADER:
  NUM_WORKERS: 10
NUM_GPUS: 32